sonar.projectKey=sq-python-scan-local
sonar.projectName="Test Python LOCAL VM"
sonar.projectVersion=1.1
sonar.host.url=http://192.168.56.10:9000

sonar.sources=.
sonar.language=py

sonar.sourceEncoding=UTF-8

#sonar.tests=tests

sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
